#! /usr/bin/env python3
# -*- mode: Python; -*-

import argparse

import aaltoasr

parser = argparse.ArgumentParser(
    description='Learn an acoustic model adaptation.',
    usage='%(prog)s [options] [-t transcript] input output',
    epilog=('For more details, see the User\'s Guide at: '
            'http://users.ics.aalto.fi/htkallas/guide.html'))

parser.add_argument('input', help='input audio file')
parser.add_argument('output', help='output adaptation file')
parser.add_argument('-t', '--trans',
                    help='input transcript for supervised adaptation',
                    metavar='file')
parser.add_argument('-v', '--verbose',
                    help='print output also from invoked commands',
                    action='store_true')
parser.add_argument('-a', '--args',
                    help='pass extra arguments to aaltoasr-rec/align',
                    metavar='A')

args = parser.parse_args()

if args.trans:
    tool = 'align'
    tool_args = ['-t', args.trans, args.input]
else:
    tool = 'rec'
    tool_args = ['-m', 'segphone', args.input]

if args.verbose:
    tool_args.append('-v')
if args.args is not None:
    tool_args.extend(args.args.strip().split())

with aaltoasr.AaltoASR(tool, args=tool_args) as asr:
    if tool == 'align':
        asr.align()
    else:
        asr.phone_probs()
        asr.rec()

    asr.adapt(args.output)
